@startuml sequence_diagram2
skinparam monochrome true
actor User as user
participant "SettingUI" as i1
participant "BranchModel" as a1
database "Database" as db

user -> i1: setDefaultBranch
activate i1

i1 -> a1: setDefaultBranch
activate a1

a1 -> db: saveDefaultBranch
activate db

db --> a1
deactivate db

a1 --> i1
deactivate a1

i1 --> user
deactivate i1

@enduml