@startuml sequence_diagram3
skinparam monochrome true
actor User as user
participant "TaskUI" as i1
participant "TaskModel" as a1
participant "BranchModel" as a2
database "Database" as db
skinparam backgroundcolor transparent

user -> i1: Set Project Tasks
activate i1

i1 -> a1: Set Project Tasks
activate a1

a1 -> a2: Verify Task Branch
activate a2
a2 -> db: Get Remote Branch
activate db
db --> a2
deactivate db
a2 --> a1
deactivate a2

alt invalid input
    a1 --> i1: Invalid input
    i1 --> user: Error input invalid
else valid input
    a1 -> db: Save Task
    activate db
    db --> a1
    deactivate db
    a1 --> i1: Tasks saved successfully
    i1 --> user: OK
end

deactivate a1
deactivate i1

@enduml