@startuml sequence_diagram5
skinparam monochrome true
actor User as user
participant "ProjectUI" as i1
participant "GitConfig" as a1
participant "TaskModel" as a2
database "Database" as db

user -> i1: viewProjectInformation
activate i1

i1 -> a1: getProjectInformation
activate a1

a1 --> i1
deactivate a1

i1 -> a2: getProjectTasks
activate a2

a2 -> db: getTasks
activate db

db --> a2
deactivate db
a2 --> i1
deactivate a2

i1 --> user
deactivate i1

@enduml