@startuml
top to bottom direction
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 14
skinparam monochrome true
hide circle

namespace contribution {
    class author << (S,Aquamarine) >> {
+ Name string
+ Email string

    }
    class authorInfo << (S,Aquamarine) >> {
+ TotalCommit int
+ LastCommit time.Time
+ FirstCommit time.Time

    }
    class ContributorData << (S,Aquamarine) >> {
- tasks []models.Task
- authorMap <font color=blue>map</font>[Author]AuthorInfo
- defaultBranchName string
- defaultRemoteName string

        + Wrapper fyne.CanvasObject

        + Render(appData *data.AppData) 
        + SetTasks(tasks []models.Task) 

    }
    class authorTable << (S,Aquamarine) >> {
- author Author
- authorInfo AuthorInfo

    }
}

"contribution.ContributorData" o-- "contribution.author"
"contribution.ContributorData" o-- "contribution.authorInfo" 
"contribution.authorTable" o-- "contribution.author"
"contribution.authorTable" o-- "contribution.authorInfo"

@enduml