@startuml
top to bottom direction
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 14
skinparam monochrome true
hide circle

namespace contribution {
    class Author << (S,Aquamarine) >> {
        + Name string
        + Email string

    }
    class AuthorInfo << (S,Aquamarine) >> {
        + TotalCommit int
        + LastCommit time.Time
        + FirstCommit time.Time

    }
    class ContributorData << (S,Aquamarine) >> {
        - authorMap <font color=blue>map</font>[Author]AuthorInfo
        - tasks []models.Task
        - defaultBranchName string
        - defaultRemoteName string

    }
    class authorTable << (S,Aquamarine) >> {
        - author Author
        - authorInfo AuthorInfo

    }
}

"contribution.ContributorData" o-- "contribution.Author"
"contribution.ContributorData" o-- "contribution.AuthorInfo" 
"contribution.authorTable" o-- "contribution.Author"
"contribution.authorTable" o-- "contribution.AuthorInfo"

@enduml