@startuml

top to bottom direction
skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 14
hide circle

namespace db {
    class DBConfig << (S,Aquamarine) >> {
        + Driver *sql.DB
        + Close <font color=blue>func</font>() 
        __
        - insertProject(p models.Project) int64
        - isTaskStatusInProgress(branchId int) bool

        + GetBranchesData(int64) : ([]models.Branch, error)
        + GetBranchById(int) : models.Branch
        + GetBranchIdByName(string) : int
        + SyncBranches(int64, []string) : error
        + GetProjects() : []models.Project
        + GetProjectByDir(string) : models.Project
        + GetTasksData(int64) : []models.Task
        + AddTask(models.Task) : error
        + DeleteTask(models.Task) : error
        + UpdateTask(models.Task) : error
        + UpdateTaskStatus(models.Task, constants.TaskStatus) : error
        + SyncTask([]models.Task, []models.Branch) : error

    }
}

@enduml
