@startuml

top to bottom direction
skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 14
hide circle

namespace db {
    class DBConfig << (S,Aquamarine) >> {
        + Driver *sql.DB
        + Close <font color=blue>func</font>() 
        __
        - insertProject(p models.Project) int64

        + GetBranchesData(projectId int64) ([]models.Branch, error)
        + GetBranchById(branchId int) models.Branch
        + GetBranchIdByName(branchName string) int
        + SyncBranches(projectId int64, branches []string) error
        + GetProjects() []models.Project
        + GetProjectByDir(dir string) models.Project
        + UpdateProject(project models.Project) error
        + GetTasksData(projectId int64) []models.Task
        + AddTask(task models.Task) error
        + DeleteTask(task models.Task) error
        + UpdateTask(task models.Task) error
        + UpdateTaskStatus(task models.Task, status constants.TaskStatus) error
        + SyncTask(tasks []models.Task, branches []models.Branch) error

    }
}

@enduml
