@startuml
top to bottom direction
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 14
skinparam monochrome true
hide circle

namespace general {
    class fileInformation << (S,Aquamarine) >> {
        + TotalFiles binding.String
        + TotalCode binding.String
        + TotalComments binding.String
        + TotalBlanks binding.String
    }

    class GeneralData << (S,Aquamarine) >> {
        - tasks []models.Task

        + ProjectDir string
        + OriginUrl string
        + ProjectName string
        + ProjectStartDate string
        + ProjectEndDate string
        + ProjectTaskStatus string
        + Commits []*object.Commit
        + Wrapper fyne.CanvasObject

        + Render(appData *data.AppData) 
        + UpdateProjectTaskStatus(appData *data.AppData) 
        + UpdateProjectStartDate(appData *data.AppData) 
        + UpdateProjectEndDate(appData *data.AppData) 

    }
}
"general.fileInformation" *-- "general.GeneralData"

@enduml