@startuml
top to bottom direction
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 14
skinparam monochrome true
hide circle

namespace git {
    class GitConfig << (S,Aquamarine) >> {
        - repo *git.Repository
        - auth transport.AuthMethod

        + GetBranchList() []string
        + GetRemoteBranches(askAuth <font color=blue>func</font>() transport.AuthMethod) ([]string, error)
        + GetLogTwoBranches(defaultBranch string, featureBranch string, remoteName string) ([]*object.Commit, error)
        + Fetch(askAuth <font color=blue>func</font>() transport.AuthMethod, defaultRemoteName string) error
        + Checkout(defaultBranchName string) error
        + FetchAndCheckout(askAuth <font color=blue>func</font>() transport.AuthMethod, defaultBranchName string, defaultRemoteName string) error
        + GetOriginUrl() string
        + GetPaths() ([]string, error)
        + GetCommitObjects() ([]*object.Commit, error)

    }
}
 
@enduml