@startuml
top to bottom direction
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 14
skinparam monochrome true
hide circle

namespace models {
    class Branch << (S,Aquamarine) >> {
        + BranchId int
        + ProjectId int
        + Name string
        + IsMergeTarget bool
        + IsDeleted bool

    }
    class Project << (S,Aquamarine) >> {
        + ProjectId int64
        + ProjectDir string
        + ProjectStartDate int64
        + ProjectEndDate int64
        + DefaultBranchName string
        + DefaultRemoteName string
        + IsFirstTime bool

    }
    class Task << (S,Aquamarine) >> {
        + TaskId int
        + ProjectId int64
        + BranchId int
        + Name string
        + AssigneeName string
        + AssigneeEmail string
        + TaskStatus int
        + StartDate int64
        + EndDate int64

    }
}
@enduml