@startuml
top to bottom direction
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 14
skinparam monochrome true
hide circle

namespace task {
    class TaskData << (S,Aquamarine) >> {
- wrapper fyne.CanvasObject

+ Project models.Project
+ Tasks []models.Task
+ Branches []models.Branch
+ AdditionalRenderers []data.Renderer

        + RefreshTasksFromTaskData(appData *data.AppData) 
        + Render(data *data.AppData) 

    }
    class formData << (S,Aquamarine) >> {
- projectId int64
- tempStartDate string
- tempEndDate string
- tempBranch string
- task models.Task
- branches []models.Branch

    }
    class taskInformation << (S,Aquamarine) >> {
- taskName string
- startDateStr string
- taskStatus constants.TaskStatus
- days int

    }
    class timelineData << (S,Aquamarine) >> {
- startDateStr string
- days int
- tasks []taskInformation

        - getGanttChartImage() []byte

    }
}

"task.TaskData" -[hidden] "task.formData"
"task.formData" -[hidden]- "task.taskInformation"
"task.formData" -[hidden]- "task.timelineData"
"task.taskInformation" -o "task.timelineData"

@enduml